"""empty message

Revision ID: e0ac85aaf18c
Revises: 
Create Date: 2020-12-18 13:17:33.917258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ac85aaf18c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('discount_band', sa.String(), nullable=True),
    sa.Column('units_sold', sa.Float(), nullable=True),
    sa.Column('manufacturing_price', sa.Float(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('gross_sales', sa.Float(), nullable=True),
    sa.Column('discounts', sa.Float(), nullable=True),
    sa.Column('sales', sa.Float(), nullable=True),
    sa.Column('cogs', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_data')
    # ### end Alembic commands ###
